# Generated by Django 5.1.6 on 2025-02-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='specialization',
        ),
        migrations.AddField(
            model_name='appointment',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.CharField(default='General', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(default='No Address provided'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='bp',
            field=models.CharField(default=1.5, help_text='Blood Pressure (e.g., 120/80)', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.FloatField(default=120, help_text='Height in cm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.FloatField(default=50, help_text='Weight in kg'),
            preserve_default=False,
        ),
    ]
