# Generated by Django 5.1.6 on 2025-02-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0002_remove_doctor_specialization_appointment_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='problem',
            field=models.TextField(default='general check up'),
            preserve_default=False,
        ),
    ]
