# Generated by Django 5.1.6 on 2025-02-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0006_remove_doctor_patients_patient_age_patient_bp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='bp',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='height',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='weight',
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(default='not specified'),
            preserve_default=False,
        ),
    ]
