# Generated by Django 5.1.6 on 2025-02-18 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0007_remove_patient_bp_remove_patient_doctor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='phone',
            new_name='contact',
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(default='not assigned', on_delete=django.db.models.deletion.CASCADE, to='hospital_app.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
